import React, { useState } from 'react';
import type{ NextPage } from 'next';
import ControleEditoras from '@/classes/controle/ControleEditora';
import { Livro } from '@/classes/modelo/Livro';
import { Menu } from '@/componentes/Menu';
import Head from 'next/head';
import Router from 'next/router';
import styles from '../styles/Home.module.css'

const controleEditora = new ControleEditoras()
const baseURL = "http://localhost:3000/api/livros";

const incluirLivro = async (livro:Livro) => {
    await fetch(baseURL,{
        method:"POST",
        body: JSON.stringify(livro)
    })
        .catch((error) => {
            console.log(error)
        });
}

const LivroDados:NextPage = () => { 
    const opcoes = controleEditora.getEditoras().map(function(editora) {
        const vetor: {
            'value':number,
            'text':string
        } = {
            'value':editora.codEditora,
            'text':editora.nome
        };
        return vetor;
    });

    const [titulo, setTitulo] = useState("");
    const [resumo, setResumo] = useState("");
    const [autores, setAutores] = useState("");
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    const tratarCombo = (e:React.ChangeEvent<HTMLSelectElement>) => setCodEditora(Number(e.target.value));

    const incluir = (e:React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        var livro = {
            codigo: 0,
            codEditora: codEditora,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n")
        }
        incluirLivro(livro);
        Router.push("/LivroLista");
    };

    return (
        <div className='styles.container'>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu/>
            <main className={styles.main}>
                <h1 className='text-center'>Dados do Livro</h1>
                <div className='container'>
                    <form onSubmit={incluir}>
                        <div className='form-group'>
                            <label htmlFor='titulo' typeof="text">Título</label><br/>
                            <input name='titulo' className="form-control" onChange={(e) => setTitulo(e.target.value)} required></input><br/>
                        </div>

                        <div className='form-group'>
                            <label htmlFor='resumo'>Resumo</label><br/>
                            <textarea name='resumo' className="form-control" onChange={(e) => setResumo(e.target.value)}></textarea><br/>
                        </div>

                        <div className='form-group'>
                            <label htmlFor='editora'>Editora</label><br/>
                            <select name='editora' className="form-control" onChange={tratarCombo}>
                                {opcoes.map((opcao, index) => (
                                    <option value={opcao.value} key={index}>{opcao.text}</option>
                                ))}
                            </select><br/>
                        </div>

                        <div className='form-group'>
                            <label htmlFor='autores'>Autores (1 por linha)</label><br/>
                            <textarea name='autores' className="form-control" onChange={(e) => setAutores(e.target.value)}></textarea><br/>
                        </div>

                        <button className='btn btn-primary' type="submit">Salvar Dados</button>
                    </form>
                </div>
            </main>
        </div>
    );
};

export default LivroDados;
